<?php

namespace ContainerRtUY5SO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U94OOMdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U94OOMd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U94OOMd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'orderProduct' => ['privates', '.errored..service_locator.U94OOMd.App\\Entity\\OrderProduct', NULL, 'Cannot autowire service ".service_locator.U94OOMd": it needs an instance of "App\\Entity\\OrderProduct" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'orderProduct' => 'App\\Entity\\OrderProduct',
        ]);
    }
}
