<?php

namespace ContainerRtUY5SO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_83uBr5LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.83uBr5L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.83uBr5L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'defects' => ['privates', '.errored..service_locator.83uBr5L.App\\Entity\\Defects', NULL, 'Cannot autowire service ".service_locator.83uBr5L": it needs an instance of "App\\Entity\\Defects" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'defects' => 'App\\Entity\\Defects',
            'entityManager' => '?',
        ]);
    }
}
