<?php

namespace ContainerRtUY5SO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C6ueBKVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c6ueBKV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c6ueBKV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'defect' => ['privates', '.errored..service_locator.c6ueBKV.App\\Entity\\Defects', NULL, 'Cannot autowire service ".service_locator.c6ueBKV": it needs an instance of "App\\Entity\\Defects" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'defect' => 'App\\Entity\\Defects',
            'entityManager' => '?',
        ]);
    }
}
