<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '1fad8eca97dc6772c36098b6b0bea566',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/data.db',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://smtp.gmail.com:465?encryption=ssl&auth_mode=login&username=melbe.na.zamowienie@gmail.com&password=wrowloijuocfypel',
);
