<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSl6Q14A\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSl6Q14A/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSl6Q14A.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSl6Q14A\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSl6Q14A\App_KernelProdContainer([
    'container.build_hash' => 'Sl6Q14A',
    'container.build_id' => '8463fe9b',
    'container.build_time' => 1707583509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSl6Q14A');
