<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin_database' => [[], ['_controller' => 'App\\Controller\\Admin\\SuperAdminDashboardController::index'], [], [['text', '/admin_database']], [], [], []],
    'app_complaints' => [[], ['_controller' => 'App\\Controller\\HomeController\\ComplaintsPageController::index'], [], [['text', '/complaints']], [], [], []],
    'app_contact' => [[], ['_controller' => 'App\\Controller\\HomeController\\ContactPageController::index'], [], [['text', '/contact']], [], [], []],
    'app_gallery' => [[], ['_controller' => 'App\\Controller\\HomeController\\GalleryPageController::index'], [], [['text', '/gallery']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\HomeController\\HomePageController::index'], [], [['text', '/']], [], [], []],
    'app_offer' => [[], ['_controller' => 'App\\Controller\\HomeController\\OfferPageController::index'], [], [['text', '/offer']], [], [], []],
    'app_orders' => [[], ['_controller' => 'App\\Controller\\HomeController\\OrdersPageController::index'], [], [['text', '/orders']], [], [], []],
    'app_pricing' => [[], ['_controller' => 'App\\Controller\\HomeController\\DefectsController::index'], [], [['text', '/pricing']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController\\LoginSecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController\\LoginSecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_change_password' => [[], ['_controller' => 'App\\Controller\\PasswordController\\ChangePasswordController::register'], [], [['text', '/change_password']], [], [], []],
    'app_reset_password' => [[], ['_controller' => 'App\\Controller\\PasswordController\\ResetPasswordController::register'], [], [['text', '/reset_password']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'homePage' => [[], ['_controller' => 'App\\Controller\\HomeController\\HomePageController::index'], [], [['text', '/']], [], [], []],
    'galleryPage' => [[], ['_controller' => 'App\\Controller\\HomeController\\GalleryPageController::index'], [], [['text', '/gallery']], [], [], []],
    'offerPage' => [[], ['_controller' => 'App\\Controller\\HomeController\\OfferPageController::index'], [], [['text', '/offer']], [], [], []],
    'contactPage' => [[], ['_controller' => 'App\\Controller\\HomeController\\ContactPageController::index'], [], [['text', '/contact']], [], [], []],
    'confirm_register' => [['code'], ['_controller' => 'App\\Controller\\RegisterController\\ConfirmController::index'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/confirm']], [], [], []],
];
