controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


homePage:
    path: /
    controller: App\Controller\HomePageController::index
galleryPage:
    path: /gallery
    controller: App\Controller\GalleryPageController::index
offerPage:
    path: /offer
    controller: App\Controller\OfferPageController::index
contactPage:
    path: /contact
    controller: App\Controller\ContactPageController::index
loginPage:
    path: /login
    controller: App\Controller\LoginController::index
confirm_register:
    path: '/confirm/{code}'
    controller: App\Controller\ConfirmController::index

