<?php

namespace ContainerWDF9Cob;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefects2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.c6ueBKV.App\Entity\Defects' shared service.
     *
     * @return \App\Entity\Defects
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.c6ueBKV": it needs an instance of "App\\Entity\\Defects" but this type has been excluded in "config/services.yaml".');
    }
}
