<?php

namespace ContainerWDF9Cob;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryPageControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Home\GalleryPageController' shared autowired service.
     *
     * @return \App\Controller\Home\GalleryPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Home'.\DIRECTORY_SEPARATOR.'GalleryPageController.php';

        $container->services['App\\Controller\\Home\\GalleryPageController'] = $instance = new \App\Controller\Home\GalleryPageController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Home\\GalleryPageController', $container));

        return $instance;
    }
}
