<?php

namespace ContainerWDF9Cob;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderProductService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.U94OOMd.App\Entity\OrderProduct' shared service.
     *
     * @return \App\Entity\OrderProduct
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.U94OOMd": it needs an instance of "App\\Entity\\OrderProduct" but this type has been excluded in "config/services.yaml".');
    }
}
