<?php

namespace ContainerSl6Q14A;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfirmControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ConfirmController' shared autowired service.
     *
     * @return \App\Controller\ConfirmController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RegisterController\\ConfirmController'] = $instance = new \App\Controller\RegisterController\ConfirmController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\RegisterController\\ConfirmController', $container));

        return $instance;
    }
}
