<?php

namespace ContainerSl6Q14A;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangePasswordControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ChangePasswordController' shared autowired service.
     *
     * @return \App\Controller\ChangePasswordController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PasswordController\\ChangePasswordController'] = $instance = new \App\Controller\Password\ChangePasswordController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PasswordController\\ChangePasswordController', $container));

        return $instance;
    }
}
