<?php

namespace ContainerSl6Q14A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ClientsRepository' shared autowired service.
     *
     * @return \App\Repository\ClientsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ClientsRepository'] = new \App\Repository\ClientsRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
