<?php

namespace ContainerSl6Q14A;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSecurityControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\LoginSecurityController' shared autowired service.
     *
     * @return \App\Controller\LoginSecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\LoginController\\LoginSecurityController'] = $instance = new \App\Controller\Login\LoginSecurityController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\LoginController\\LoginSecurityController', $container));

        return $instance;
    }
}
