<?php

namespace ContainerSl6Q14A;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrdersPageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\OrdersPageController' shared autowired service.
     *
     * @return \App\Controller\OrdersPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\HomeControllers\\OrdersPageController'] = $instance = new \App\Controller\Home\OrdersPageController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\HomeControllers\\OrdersPageController', $container));

        return $instance;
    }
}
