<?php

namespace ContainerSl6Q14A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ResetPasswordForm' shared autowired service.
     *
     * @return \App\Form\ResetPasswordForm
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ResetPasswordForm'] = new \App\Form\ResetPasswordForm();
    }
}
