<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ6tJy9m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ6tJy9m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ6tJy9m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ6tJy9m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ6tJy9m\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z6tJy9m',
    'container.build_id' => '2fcd4eb2',
    'container.build_time' => 1708511263,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ6tJy9m');
