<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xDV1vW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xDV1vW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6xDV1vW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6xDV1vW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6xDV1vW\App_KernelDevDebugContainer([
    'container.build_hash' => '6xDV1vW',
    'container.build_id' => '1977a143',
    'container.build_time' => 1708365550,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6xDV1vW');
