<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWDF9Cob\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWDF9Cob/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWDF9Cob.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWDF9Cob\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWDF9Cob\App_KernelDevDebugContainer([
    'container.build_hash' => 'WDF9Cob',
    'container.build_id' => '9b1dfc62',
    'container.build_time' => 1734129800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWDF9Cob');
