<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_tailwindcss_base_css-node_modules_tailwindcss_components_css-node_module-5a2d3e.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_tailwindcss_base_css-node_modules_tailwindcss_components_css-node_module-5a2d3e.css',
                '/build/app.css',
            ],
        ],
    ],
],

]];
